import { useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppHeader } from "@/components/navigation/AppHeader";
import { AppIcon } from "@/components/ui/AppIcon";
import { FontSizes, Fonts, Radius, Spacing } from "@/constants/theme";
import { useCart } from "@/context/CartContext";
import { useAuth } from "@/context/AuthContext";
import { useTheme } from "@/context/ThemeContext";
import { supabase } from "@/lib/supabase";

type Status = "pending" | "confirmed" | "preparing" | "ready" | "out_for_delivery" | "delivered" | "cancelled";
type Item = { id: string; product_name: string; selling_unit: string; quantity: number; unit_price: number; line_total: number };
type SubOrder = { id: string; status: Status; subtotal: number; store_delivery_enabled: boolean; stores: { name: string } | { name: string }[] | null; order_items: Item[] };
type Order = { id: string; customer_id: string; order_number: number; status: Status; created_at: string; currency: string; subtotal: number; delivery_fee: number; total: number; payment_method: string; customer_note: string; sub_orders: SubOrder[] };
const statusLabels: Record<Status, string> = { pending: "بانتظار التأكيد", confirmed: "تم التأكيد", preparing: "قيد التجهيز", ready: "جاهز", out_for_delivery: "في الطريق", delivered: "تم التسليم", cancelled: "ملغى" };
const unitLabels: Record<string, string> = { kg: "كغ", g: "غ", liter: "لتر", ml: "مل", piece: "قطعة", pack: "عبوة" };

export default function OrderDetailsScreen() {
  const params = useLocalSearchParams<{ id?: string }>(); const orderId = typeof params.id === "string" ? params.id : "";
  const { colors } = useTheme(); const { itemCount } = useCart(); const { user } = useAuth(); const [order, setOrder] = useState<Order | null>(null); const [loading, setLoading] = useState(true); const [cancelling, setCancelling] = useState(false);
  const refresh = useCallback(async () => { if (!orderId) { setLoading(false); return; } setLoading(true); const { data, error } = await supabase.from("orders").select("id,customer_id,order_number,status,created_at,currency,subtotal,delivery_fee,total,payment_method,customer_note,sub_orders(id,status,subtotal,store_delivery_enabled,stores(name),order_items(id,product_name,selling_unit,quantity,unit_price,line_total))").eq("id", orderId).maybeSingle(); if (error) Alert.alert("تعذر تحميل الطلب", "تحقق من اتصالك بالإنترنت وحاول مجدداً."); setOrder(data as unknown as Order | null); setLoading(false); }, [orderId]);
  useEffect(() => { const timer = setTimeout(() => { void refresh(); }, 0); return () => clearTimeout(timer); }, [refresh]);
  const money = (n: number) => `${Number(n).toLocaleString("en-US")} ${order?.currency === "USD" ? "$" : "ل.س"}`;
  const cancelOrder = () => Alert.alert("إلغاء الطلب", "هل تريد إلغاء هذا الطلب؟", [{ text: "رجوع", style: "cancel" }, { text: "إلغاء الطلب", style: "destructive", onPress: () => { void (async () => { setCancelling(true); const { error } = await supabase.rpc("cancel_customer_order", { target_order: orderId, note: "إلغاء من قبل الزبون" }); setCancelling(false); if (error) Alert.alert("تعذر الإلغاء", "بدأ أحد المتاجر التحضير أو لم يعد الطلب قابلاً للإلغاء."); else { await refresh(); Alert.alert("تم الإلغاء", "تم إلغاء الطلب."); } })(); } }]);
  const canCancel = !!order && order.customer_id === user?.id && ["pending", "confirmed"].includes(order.status) && !order.sub_orders?.some((sub) => ["preparing", "ready", "out_for_delivery", "delivered"].includes(sub.status));
  return <View style={[styles.container, { backgroundColor: colors.background }]}><AppHeader title="تفاصيل الطلب" showBack cartCount={itemCount} showMarketplaceActions={false} />
    {loading ? <ActivityIndicator color={colors.primary} style={styles.loading} /> : !order ? <View style={styles.loading}><Text style={{ color: colors.textSecondary }}>لم يتم العثور على الطلب.</Text></View> : <ScrollView contentContainerStyle={styles.content}>
      <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.overline, { color: colors.textMuted }]}>رقم الطلب</Text><Text style={[styles.heading, { color: colors.text }]}>#{order.order_number}</Text><Text style={[styles.date, { color: colors.textSecondary }]}>{new Date(order.created_at).toLocaleString("ar-SY")}</Text><View style={[styles.status, { backgroundColor: order.status === "cancelled" ? colors.error + "18" : colors.primaryLight }]}><Text style={{ color: order.status === "cancelled" ? colors.error : colors.primary, fontFamily: Fonts.semiBold }}>{statusLabels[order.status]}</Text></View></View>
      <Text style={[styles.sectionTitle, { color: colors.text }]}>المتاجر والمنتجات</Text>
      {order.sub_orders?.map((sub) => { const store = Array.isArray(sub.stores) ? sub.stores[0] : sub.stores; return <View key={sub.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.storeHeader}><AppIcon name="storefront-outline" size={21} color={colors.primary} /><Text style={[styles.storeName, { color: colors.text }]}>{store?.name ?? "المتجر"}</Text><Text style={{ color: colors.accent }}>{statusLabels[sub.status]}</Text></View>{sub.order_items?.map((item) => <View key={item.id} style={[styles.item, { borderTopColor: colors.border }]}><View style={styles.itemCopy}><Text style={[styles.itemName, { color: colors.text }]}>{item.product_name}</Text><Text style={[styles.itemMeta, { color: colors.textSecondary }]}>{item.quantity} {unitLabels[item.selling_unit] ?? item.selling_unit} × {money(item.unit_price)}</Text></View><Text style={[styles.itemPrice, { color: colors.text }]}>{money(item.line_total)}</Text></View>)}</View>; })}
      <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.text }]}>ملخص الطلب</Text><Summary label="إجمالي المنتجات" value={money(order.subtotal)} /><Summary label="التوصيل" value={money(order.delivery_fee)} /><Summary label="الإجمالي" value={money(order.total)} strong /></View>
      <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.text }]}>الدفع</Text><Text style={[styles.itemMeta, { color: colors.textSecondary }]}>{order.payment_method === "cash" ? "الدفع نقداً عند الاستلام" : order.payment_method}</Text></View>
      {canCancel ? <Pressable disabled={cancelling} onPress={cancelOrder} style={[styles.cancel, { borderColor: colors.error }]}><Text style={{ color: colors.error, fontFamily: Fonts.semiBold }}>{cancelling ? "جارٍ الإلغاء…" : "إلغاء الطلب"}</Text></Pressable> : null}
    </ScrollView>}
  </View>;
}
function Summary({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { const { colors } = useTheme(); return <View style={styles.summary}><Text style={{ color: strong ? colors.primary : colors.textSecondary, fontFamily: strong ? Fonts.bold : Fonts.regular }}>{label}</Text><Text style={{ color: strong ? colors.primary : colors.text, fontFamily: strong ? Fonts.bold : Fonts.medium }}>{value}</Text></View>; }
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: Spacing.four, paddingBottom: Spacing.ten }, loading: { flex: 1, alignItems: "center", justifyContent: "center" }, card: { padding: Spacing.four, marginBottom: Spacing.three, borderWidth: 1, borderRadius: Radius.xl }, overline: { textAlign: "right", fontSize: FontSizes.xs }, heading: { textAlign: "right", marginTop: 4, fontFamily: Fonts.bold, fontSize: FontSizes.xl }, date: { textAlign: "right", marginTop: 4, fontSize: FontSizes.xs }, status: { alignSelf: "flex-end", marginTop: Spacing.three, paddingHorizontal: Spacing.three, paddingVertical: 6, borderRadius: Radius.full }, sectionTitle: { marginBottom: Spacing.three, textAlign: "right", fontFamily: Fonts.bold, fontSize: FontSizes.md }, storeHeader: { flexDirection: "row-reverse", alignItems: "center", gap: 8, marginBottom: Spacing.two }, storeName: { flex: 1, textAlign: "right", fontFamily: Fonts.bold }, item: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", paddingVertical: Spacing.three, borderTopWidth: 1 }, itemCopy: { flex: 1, alignItems: "flex-end" }, itemName: { textAlign: "right", fontFamily: Fonts.medium }, itemMeta: { marginTop: 4, fontSize: FontSizes.xs, textAlign: "right" }, itemPrice: { marginStart: Spacing.two, fontFamily: Fonts.semiBold, fontSize: FontSizes.xs }, summary: { flexDirection: "row-reverse", justifyContent: "space-between", paddingVertical: 7 }, cancel: { alignItems: "center", padding: Spacing.four, borderWidth: 1, borderRadius: Radius.lg } });
